version: '3'
services:
  web:
    build: .
    environment: 
      - SERVER_ADDRESS=8080
    ports:
      - "8080:8080"
    links:
      - "db:mongodb"
      - "centrifugo:io"
  db:
    image: "mongo"
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
  centrifugo:
    build: ./centrifugo
    ports:
      - "8081:8081"
      - "9000:9000"
    links:
      - "redis:redis_host"